import { Project } from "./project";

export const seedProjects = [
  new Project({
    id: "openruleta",
    title: "OpenRuleta",
    slug: "openruleta",
    summary:
      "Toolkit de sorteo para eventos, self-hostable: un formulario público de inscripción (deployable) y una rueda de ganadores para el operador (local o detrás de una contraseña). Usado en vivo en Data Saturday LATAM Argentina 2026 con ~300 inscripciones en simultáneo.",
    description:
      "Monorepo pnpm con dos apps Next.js 16 sobre una sola tabla de Supabase. apps/form es la parte pública (Next estático deployable en Vercel): usa la anon key, que por RLS solo puede INSERT en participants, con honeypot anti-bot e índice único por email que rechaza duplicados con 409. apps/ruleta es la rueda que se proyecta en el evento: usa la service_role key (SELECT/UPDATE/DELETE), así que corre local — o hosteada detrás de HTTP Basic Auth activado con una sola variable de entorno. Tres paquetes compartidos (config, core, ui): TODO lo configurable — nombre del evento, textos, reglas del campo de documento, sponsors, tiempos de la rueda, colores del confeti, columnas del CSV — vive en un único archivo. El ganador se saca del bombo con won_at y el premio del modal se pre-carga con el título del sorteo. Se usó en el evento real con ~300 asistentes inscribiéndose desde el celular en simultáneo, todo sobre un proyecto de Supabase del plan gratuito.",
    stack: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind",
      "Supabase",
      "PostgreSQL",
      "pnpm workspaces",
    ],
    githubUrl: "https://github.com/LorenGrz/OpenRuleta",
    liveUrl: "https://lorengrz.github.io/landing-openruleta/",
    status: "completed",
    featured: true,
    images: [
      {
        url: "https://images.unsplash.com/photo-1625888791210-40ea41c1d0f3?auto=format&fit=crop&w=1200&q=80",
        alt: "Rueda de ruleta clásica de madera con fichas de casino al fondo.",
      },
    ],
    createdAt: new Date("2026-09-06T00:00:00.000Z").toISOString(),
    updatedAt: new Date("2026-09-06T00:00:00.000Z").toISOString(),
  }),
  new Project({
    id: "contentcreator",
    title: "ContentCreator",
    slug: "contentcreator",
    summary: "Bot serverless que cada día lee mi actividad real (GitHub, Hacker News, cuentas de X) y redacta borradores de tweets y posts de LinkedIn para que los apruebe por Telegram. No publica solo.",
    description:
      "Una función Lambda (FastAPI + Mangum) que una vez al día ingiere señales de fuentes reales: eventos de GitHub (commits, PRs, repos nuevos), Hacker News y, opcionalmente, tweets de cuentas seguidas vía un puente RSS de Nitter. Un modelo de Amazon Bedrock (Strands Agents SDK) redacta tweets cortos y, solo cuando una compuerta de significancia basada en reglas lo justifica, un post de LinkedIn. Todo se guarda en una única tabla de DynamoDB y se envía a Telegram con botones Aprobar / Descartar / Editar; editar abre un loop de reescritura conversacional. Si un borrador nace de un tweet de una cuenta seguida, propone un quote tweet con mi ángulo en vez de un post original. Publicar siempre es manual. Secretos en SSM Parameter Store, despliegue con AWS SAM, corrida diaria por EventBridge Scheduler. 63 tests unitarios.",
    stack: [
      "Python",
      "FastAPI",
      "AWS Lambda",
      "Amazon Bedrock",
      "Strands Agents",
      "DynamoDB",
      "AWS SAM",
      "EventBridge",
      "Telegram Bot API",
    ],
    githubUrl: "https://github.com/LorenGrz/ContentCreator",
    repositoryNote: "Bot personal: corre en mi cuenta de AWS, sin publicación automática.",
    status: "completed",
    featured: true,
    images: [
      {
        url: "/contentcreator.png",
        alt: "Conversación de Telegram con el bot: un borrador de tweet con botones Aprobar y Descartar.",
      },
    ],
    createdAt: new Date("2026-09-02T00:00:00.000Z").toISOString(),
    updatedAt: new Date("2026-09-02T00:00:00.000Z").toISOString(),
  }),
  new Project({
    id: "humandetector",
    title: "HumanDetector",
    slug: "humandetector",
    summary: "Instalación satírica de \"verificación de humanidad\": pide gestos por cámara, escala los pedidos hasta lo imposible y nunca aprueba.",
    description:
      "Verificador de humanidad para una antihackathon. El frontend (Next.js export estático en GitHub Pages) captura la cámara y la manda por WebSocket a un backend FastAPI que hace detección real de gestos con MediaPipe (parpadeo, giro de cabeza, inclinación, boca) y corre una máquina de estados de 10 pasos que escala la exigencia hasta pedidos absurdos. Backend contenerizado en EC2 con Caddy y TLS automático de Let's Encrypt; imagen construida en AWS CodeBuild y publicada en ECR. Sin base de datos: todo el estado vive en memoria por conexión.",
    stack: [
      "Next.js",
      "TypeScript",
      "Tailwind",
      "Python",
      "FastAPI",
      "MediaPipe",
      "WebSockets",
      "Docker",
      "AWS EC2",
      "AWS ECR",
      "Caddy",
    ],
    githubUrl: "https://github.com/LorenGrz/HumanDetector",
    liveUrl: "https://lorengrz.github.io/landing-humandetector/",
    repositoryNote: "Backend on-demand: se enciende para demos y eventos.",
    status: "completed",
    featured: true,
    images: [
      {
        url: "/humandetector.png",
        alt: "Pantalla de inicio de HumanDetector con el mensaje \"¿Sos humano?\" y el botón Comenzar verificación.",
      },
    ],
    createdAt: new Date("2026-08-29T00:00:00.000Z").toISOString(),
    updatedAt: new Date("2026-08-29T00:00:00.000Z").toISOString(),
  }),
  new Project({
    id: "prioria",
    title: "Prioria",
    slug: "prioria",
    summary: "App Android que intercepta notificaciones, las prioriza con un agente de IA y las muestra en un widget. TTS automático vía Amazon Polly.",
    description:
      "MVP Android-first construido con Expo (SDK 57) y React Native. Un agente serverless (Strands Agents SDK + Bedrock) analiza cada notificación según las preferencias y reglas del usuario y le asigna un score de prioridad. Las críticas se envían al widget vía FCM y se leen por voz con Amazon Polly (voces Lucía/Enrique). El usuario refuerza el modelo con feedback explícito (👍/👎), apertura desde el widget y conversación directa con el agente en la pantalla Entrenar. Backend 100% serverless AWS: SAM, Lambda (Node 24 + Python 3.13), API Gateway, Cognito, DynamoDB, SQS.",
    stack: [
      "React Native",
      "Expo",
      "NativeWind",
      "TypeScript",
      "AWS Lambda",
      "API Gateway",
      "Amazon Cognito",
      "DynamoDB",
      "Amazon Polly",
      "Strands Agents",
      "Amazon Bedrock",
      "AWS SAM",
      "Next.js",
    ],
    githubUrl: "https://github.com/LorenGrz/Prioria",
    liveUrl: "https://lorengrz.github.io/landing-prioria/",
    status: "in_progress",
    featured: true,
    images: [
      {
        url: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=1200&q=80",
        alt: "Pantalla de smartphone con burbujas de notificación, representando una app de priorización de notificaciones con IA.",
      },
    ],
    createdAt: new Date("2026-08-04T00:00:00.000Z").toISOString(),
    updatedAt: new Date("2026-08-04T00:00:00.000Z").toISOString(),
  }),
  new Project({
    id: "serverlessscanner",
    title: "ServerlessScanner",
    slug: "serverlessscanner",
    summary: "Herramienta de análisis de arquitectura AWS que detecta oportunidades de migración serverless en stacks CloudFormation.",
    description:
      "API en FastAPI que analiza templates de CloudFormation e identifica recursos (EC2, RDS, ECS, etc.) que pueden migrarse a Lambda, Aurora Serverless, DynamoDB y otros servicios serverless, estimando el ahorro de costos potencial.",
    stack: ["Python", "FastAPI", "AWS Lambda", "API Gateway", "AWS SAM"],
    githubUrl: "https://github.com/LorenGrz/ServerlessScanner",
    liveUrl: "https://lorengrz.github.io/landing-serverlessscanner/",
    status: "completed",
    featured: true,
    images: [
      {
        url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
        alt: "Diagrama de infraestructura en la nube, representando el análisis de arquitectura serverless.",
      },
    ],
    createdAt: new Date("2026-07-10T00:00:00.000Z").toISOString(),
    updatedAt: new Date("2026-07-10T00:00:00.000Z").toISOString(),
  }),
  new Project({
    id: "studyquest",
    title: "StudyQuest",
    slug: "studyquest",
    summary: "Plataforma de estudio full-stack con quizzes generados por IA y sistema de matching de usuarios.",
    description:
      "Plataforma en desarrollo que convierte archivos PDF/DOCX en quizzes interactivos, con una API modular en NestJS, PostgreSQL, Redis y Docker Compose.",
    stack: ["React", "TypeScript", "Tailwind", "NestJS", "PostgreSQL", "Redis", "Docker Compose"],
    githubUrl: "https://github.com/LorenGrz/StudyQuest",
    liveUrl: "https://lorengrz.github.io/landing-studyquest/",
    status: "in_progress",
    featured: true,
    images: [
      {
        url: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
        alt: "Laptop mostrando una interfaz de aprendizaje para una plataforma de estudio online.",
      },
    ],
    createdAt: new Date("2026-06-01T00:00:00.000Z").toISOString(),
    updatedAt: new Date("2026-06-01T00:00:00.000Z").toISOString(),
  }),
  new Project({
    id: "frauddetector",
    title: "FraudDetector",
    slug: "frauddetector",
    summary: "Herramienta de detección de fraude bancario que analiza 100k+ transacciones usando consenso de 3 modelos ML y visualiza el riesgo en un dashboard interactivo.",
    description:
      "Procesa datasets de 100k+ transacciones bancarias para identificar clientes y operaciones sospechosas. Tres modelos de ML no supervisado (Isolation Forest, LOF, K-Means) analizan cada caso en paralelo: un cliente se marca como riesgo solo cuando ≥ 2 modelos coinciden, lo que reduce falsos positivos un ~35% frente a un modelo único. El dashboard interactivo (Plotly) muestra la distribución de riesgo por cliente, compara perfiles y permite inspeccionar transacciones individuales con scatter plots y boxplots. API REST con tiempos de respuesta de 110–150 ms por análisis de cliente y 40–60 ms por transacción.",
    stack: ["Python", "FastAPI", "scikit-learn", "SQLite", "SQLAlchemy", "Plotly", "Bootstrap"],
    githubUrl: "https://github.com/LorenGrz/FraudDetector",
    liveUrl: "https://lorengrz.github.io/landing-frauddetector/",
    status: "completed",
    featured: true,
    images: [
      {
        url: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80",
        alt: "Visualización de datos abstracta, representando analítica de detección de fraude.",
      },
    ],
    createdAt: new Date("2026-04-15T00:00:00.000Z").toISOString(),
    updatedAt: new Date("2026-04-15T00:00:00.000Z").toISOString(),
  }),
  new Project({
    id: "booklibre",
    title: "BookLibre",
    slug: "booklibre",
    summary: "Sistema de reserva y alquiler de libros con stack full-stack completamente dockerizado.",
    description:
      "Sistema de reserva y alquiler usando React, TypeScript, Chakra UI, Kotlin, Spring Boot, Docker Compose y persistencia políglota con PostgreSQL, MongoDB y Redis.",
    stack: ["React", "TypeScript", "Chakra UI", "Kotlin", "Spring Boot", "Docker Compose"],
    githubUrl: "https://github.com/LorenGrz/BookLibre",
    liveUrl: "https://lorengrz.github.io/landing-booklibre/",
    repositoryNote: "Proyecto académico grupal — UNSAM.",
    status: "completed",
    featured: true,
    images: [
      {
        url: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=1200&q=80",
        alt: "Estanterías de biblioteca, representando una plataforma de reserva de libros.",
      },
    ],
    createdAt: new Date("2026-02-01T00:00:00.000Z").toISOString(),
    updatedAt: new Date("2026-02-01T00:00:00.000Z").toISOString(),
  }),
  new Project({
    id: "algo-que-pedir",
    title: "Algo Que Pedir",
    slug: "algo-que-pedir",
    summary: "Aplicación full-stack académica estilo PedidosYa para gestión de productos, órdenes y usuarios.",
    description:
      "Proyecto académico grupal con frontends SPA, backend REST, arquitectura por capas, flujo de PRs en GitHub y Docker Compose.",
    stack: ["React", "Svelte", "TypeScript", "Tailwind", "Kotlin", "Spring Boot", "Docker Compose"],
    githubUrl: "https://github.com/LorenGrz/AlgoQuePedir",
    repositoryNote: "Proyecto académico grupal — UNSAM.",
    status: "completed",
    featured: true,
    images: [
      {
        url: "https://images.unsplash.com/photo-1526367790999-0150786686a2?auto=format&fit=crop&w=1200&q=80",
        alt: "Pantalla de pedido de comida representando una aplicación estilo PedidosYa.",
      },
    ],
    createdAt: new Date("2025-11-01T00:00:00.000Z").toISOString(),
    updatedAt: new Date("2025-11-01T00:00:00.000Z").toISOString(),
  }),
] as const;
